# CircleCI configuration file
version: 2.1

parameters:
  BRANCH_NAME:
    type: string
    default: ''

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"

  after-branch-deletion:
    docker:
      - image: cimg/base:2022.05
    parameters:
      BRANCH_NAME:
        type: string
        default: << pipeline.parameters.BRANCH_NAME >>
    steps:
      - run: echo "YAEH the branch has been deleted"
      - run:
          name: Clean up resources -
          command: |
            DELETED_BRANCH_NAME= << parameters.BRANCH_NAME >>
            echo "Cleaning up resources for branch: $DELETED_BRANCH_NAME"

workflows:
  clean-up:
    jobs:
      - after-branch-deletion
