# CircleCI configuration file
version: 2.1

parameters:
  branch_name:
    type: string
    default: 'EMPTY'

jobs:
  after-branch-deletion:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "YAEH the branch has been deleted"
      - run:
          name: Clean up resources
          command: |
            echo "Cleaning up resources for branch: ${BRANCH}"
    environment:
      - BRANCH: << pipeline.parameters.branch_name >>

workflows:
  clean-up:
    jobs:
      - after-branch-deletion
