# CircleCI configuration file
version: 2.1

parameters:
  BRANCH_NAME2:
    type: string
    default: ''

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"

  after-branch-deletion:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "YAEH the branch has been deleted"
      - run:
          name: Clean up resources -
          command: |
            echo "Cleaning up resources for branch: $BRANCH_NAME"

workflows:
  clean-up:
    jobs:
      - after-branch-deletion
