name: Trigger CircleCI Pipeline

on:
  delete:
    branches:
      - '*'

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/setup-git@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract branch name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Trigger CircleCI pipeline
        run: |
          curl -X POST 'https://circleci.com/api/v2/project/gh/yevheniydomin/githubwebhooks_test/pipeline' \
          --header "Circle-Token: $CIRCLECI_API_TOKEN" \
          --header "content-type: application/json" \
          --data '{"branch": "main", "parameters": {"branch_name": "${BRANCH_NAME}"}}'
        env:
          BRANCH_NAME: ${{ steps.branch_name.outputs.BRANCH_NAME }}
          CIRCLECI_API_TOKEN: ${{ secrets.CIRCLECI_API_TOKEN }}
