name: Branch Deletion

on:
  delete:
    branches:
      filter:
        - main

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger circleci clean up job
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: ${{secrets.CIRCLECI_TOKEN}}
