name: Branch Deletion

on:
  delete:
    branches:
      - '*'

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger circleci clean up job
        uses: circleci/githubwebhooks_test
        env:
          CCI_TOKEN: ${{secrets.CIRCLECI_TOKEN}}
