name: Branch Deletion

on:
  delete:
    branches:
      - '*'

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: githubwebhooks_test
        id: cb4b5e56-6e37-4da4-a9a5-f238088ebb52
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          node-version: '18.x'
        env:
          CCI_TOKEN: ${{secrets.CIRCLECI_TOKEN}}
